# Converted from depth_color.ipynb
# Conversion time: 2025-10-22T07:31:44.132245
# This file was auto-generated by ChatGPT.
# Code cells are preserved. Markdown cells are added as commented blocks.

# --- Code cell 0 ---
import numpy as np
import matplotlib.pyplot as plt
import PIL.Image as pil
import os

os.chdir("/media/mems509/9b308a11-7150-4494-8f42-71df9385ff43/home/mems509/hz/MonoLoT-main")

# imgs = ["data/c3vd_v2/imgs/cecum_t4_b_under_review/0000_color.png",
#         "data/c3vd_v2/imgs/desc_t4_a_under_review/0100_color.png",
#         "data/c3vd_v2/imgs/sigmoid_t3_b_under_review/0500_color.png",
#         "data/c3vd_v2/imgs/trans_t4_b_under_review/0400_color.png"]

imgs = ["data/c3vd_v2/imgs/cecum_t4_b_under_review/0028_color.png",
        "data/c3vd_v2/imgs/desc_t4_a_under_review/0020_color.png",
        "data/c3vd_v2/imgs/sigmoid_t3_b_under_review/0025_color.png",
        "data/c3vd_v2/imgs/trans_t4_b_under_review/0090_color.png"]

"""
imgs = [
    "data/c3vd_v2/imgs/cecum_t4_b_under_review/0060_color.png",
    # "data/c3vd_v2/imgs/cecum_t4_b_under_review/0000_color.png",
    "data/c3vd_v2/imgs/desc_t4_a_under_review/0030_color.png",
    # "data/c3vd_v2/imgs/desc_t4_a_under_review/0095_color.png",
    "data/c3vd_v2/imgs/sigmoid_t3_b_under_review/0120_color.png",
    # "data/c3vd_v2/imgs/sigmoid_t3_b_under_review/0000_color.png",
    "data/c3vd_v2/imgs/trans_t4_b_under_review/0455_color.png",
    # "data/c3vd_v2/imgs/trans_t4_b_under_review/0480_color.png",
]
"""
for img in imgs:
    fname = os.path.join(
        "/media/mems509/9b308a11-7150-4494-8f42-71df9385ff43/home/mems509/hz/MonoLoT-main", img)
    gt = pil.open(fname.replace("color.png", "depth.tiff"))
    gt = np.array(gt, np.float32) / (2 ** 16 - 1)

    fig, axes = plt.subplots(1, 1)
    fig.set_size_inches(10, 10)
    im = axes.imshow(gt, cmap="jet_r", vmin=0, vmax=1)
    # axes.imshow(1-gt, vmin=0, vmax=1)
    axes.axis('off')
    fname_colormap = "_".join(img.split("/")[-2:] )
    #plt.savefig(os.path.join("gt_color_map", fname_colormap), bbox_inches='tight', pad_inches=0)
# axes[1].imshow(depths[idx].max() - depths[idx], cmap="jet")
# axes[1].axis('off')


# --- Code cell 1 ---
fig, axes = plt.subplots(1, 1)
fig.set_size_inches(10, 6)
im = axes.imshow(gt, cmap="jet_r", vmin=0, vmax=1)
# axes.imshow(1-gt, vmin=0, vmax=1)
axes.axis('off')
plt.colorbar(im, ax=axes, aspect=12, drawedges=False, ticks=[0, 1])

# --- Code cell 2 ---
import os

os.chdir("/media/mems509/9b308a11-7150-4494-8f42-71df9385ff43/home/mems509/hz/MonoLoT-main")
from depthnet.utils import *
from depthnet.model import EstimateDepth
from pathlib import Path
import glob
import torchvision
from torchvision import transforms

model_list = ["RCC_matching_cropalign_depthnet_c3vd_v2_monodepth2"]

#model_list = ["RCC"]
model_pred_depths = []


def pil_loader(path):
    # open path as file to avoid ResourceWarning
    # (https://github.com/python-pillow/Pillow/issues/835)
    with open(path, 'rb') as f:
        with Image.open(f) as img:
            return img.convert('RGB')


for model_name in model_list:
    # path of model
    # model_name = "RC_matching_depthnet_c3vd_v2_litemono_sd0"

    device = f'cuda:0'
    gpu_id = 0
    if gpu_id is not None:
        os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
        os.environ["CUDA_VISIBLE_DEVICES"] = str(gpu_id)
    if torch.cuda.is_available():
        torch.backends.cudnn.enabled = True
        torch.backends.cudnn.benchmark = False
        torch.backends.cudnn.deterministic = True

    cfgs = load_yaml(
        "/media/mems509/9b308a11-7150-4494-8f42-71df9385ff43/home/mems509/hz/MonoLoT-main/results/RCC_matching_cropalign_depthnet_c3vd_v2_monodepth2_rep0/models/configs.yml")
    cfgs.update({'device': device, "not_load_nets": ["net_pose_encoder", "net_pose_decoder", "net_depth_intrinsics"]})


    def getDepthNet():
    # cp_path = Path('results') / model_name / "models" / "weights_18"
        #cp_path = Path('newresultsbest_bestcamera_attention_lightweightdepthdecoder') / model_name / "models" / "weights_23"
        cp_path = Path('newresultsbest_bestcamera_attention') / model_name / "models" / "weights_23"
        #cp_path = Path('newresults_0.15_0.15') / model_name / "models" / "weights_22"
    # cp_path = Path极市results') / model_name / "models" / "weights_last"

        model = globals().get(cfgs.get('model'))(cfgs)

        cp = {}
        for network_name in model.network_names:
            cp[network_name] = torch.load(cp_path / "{}.pth".format(network_name), map_location=device)

        model.load_model_state(cp)

        return model

    model = getDepthNet()
    model.to_device(device)

    # load
    import os
    import torch
    from torchvision import transforms
    import cv2
    import numpy as np
    from tqdm.auto import tqdm
    from PIL import Image

    from depthnet.networks.layers import disp_to_depth
    from depthnet.utils import readlines
    import depthnet.networks as networks
    from depthnet.networks.layers import transformation_from_parameters

    exps = [cfgs["model_name"]]

    height = cfgs.get('height', 256)
    width = cfgs.get('width', 320)
    model.set_eval()

    pred_depths = []

    print("-> Computing predictions with size {}x{}".format(width, height))

    MIN_DEPTH = 0.001
    MAX_DEPTH = 1.

    with torch.no_grad():
        for fname in tqdm(imgs):
            gt_depth = cv2.imread(fname.replace("color.png", "depth.tiff"), -1)
            gt_depth = gt_depth / (2 ** 16 - 1)
            gt_height, gt_width = gt_depth.shape[:2]

            input_color = pil_loader(fname)
            input_color = transforms.Resize((height, width), torchvision.transforms.InterpolationMode.LANCZOS)(
                input_color)

            # input_color2 = cv2.imread(fname)
            # input_color2 = cv2.resize(input_color2, (width, height))
            # rgb = rgb[:, :, ::-1]

            input_color = transforms.ToTensor()(input_color).unsqueeze(0).to(device)
            # input_color2 = transforms.ToTensor()(input_color2).unsqueeze(0).to(device)

            # input_color = cv2.imread(fname)
            # input_color = cv2.resize(input_color, (width, height))
            # # rgb = rgb[:, :, ::-1]
            # input_color = transforms.ToTensor()(input_color).unsqueeze(0).to(device)

            output = model.net_depth_decoder(model.net_depth_encoder(input_color))

            pred_disp, _ = disp_to_depth(output[("disp", 0)], cfgs["min_depth"], cfgs["max_depth"])

            pred_disp = pred_disp.cpu()[0, 0, :, :].numpy()
            pred_disp = cv2.resize(pred_disp, (gt_width, gt_height))
            pred_depth = 1 / pred_disp

            ratio = np.median(gt_depth) / np.median(pred_depth)
            pred_depth *= ratio

            pred_depth[pred_depth < MIN_DEPTH] = MIN_DEPTH
            pred_depth[pred_depth > MAX_DEPTH] = MAX_DEPTH

            pred_depths.append(pred_depth)

    model_pred_depths.append(pred_depths)


# --- Code cell 3 ---

def compute_errors(gt, pred):
    thresh = np.maximum((gt / pred), (pred / gt))
    a1 = (thresh < 1.25).mean()
    a2 = (thresh < 1.25 ** 2).mean()
    a3 = (thresh < 1.25 ** 3).mean()

    rmse = (gt - pred) ** 2
    rmse = np.sqrt(rmse.mean())

    rmse_log = (np.log(gt) - np.log(pred)) ** 2
    rmse_log = np.sqrt(rmse_log.mean())

    abs_rel = np.mean(np.abs(gt - pred) / gt)

    sq_rel = np.mean(((gt - pred) ** 2) / gt)

    return [abs_rel, sq_rel, rmse, rmse_log, a1, a2, a3]


fig, axes = plt.subplots(len(imgs), 8)
fig.set_size_inches(42, 20)
axes = axes.flatten()

rmse = np.zeros((len(imgs), 6))

for i, model_name in enumerate(model_list):
    print(model_name)
    print("\n  " + ("{:>8} | " * 7).format("abs_rel", "sq_rel", "rmse", "rmse_log", "a1", "a2", "a3"))
    for j, img in enumerate(imgs):
        pred_depth = model_pred_depths[i][j]
        axes[8 * j + 2 + i].imshow(pred_depth, cmap="jet_r", vmin=0, vmax=1)
        axes[8 * j + 2 + i].axis('off')

        gt_depth = cv2.imread(img.replace("color.png", "depth.tiff"), -1)
        gt_depth = gt_depth / (2 ** 16 - 1)
        # axes.imshow(1-pred_depth, vmin=0, vmax=1)

        mean_errors = compute_errors(gt_depth, pred_depth)
        print(("&{: 8.3}  " * 7).format(*mean_errors))

        # axes[18 * j + i].set_title("{:.3f}".format(mean_errors[2]), y=-0.14, size=36)
        rmse[j, i] = mean_errors[2]
        # fontweight='bold'

        if i == 0:
            # input_color = cv2.imread(fname)
            # rgb = cv2.resize(input_color, (width, height))
            input_color = pil_loader(img)
            axes[8 * j + 0].imshow(input_color)
            axes[8 * j + 0].axis('off')

            # axes[8 * j + 1].imshow(gt_depth, cmap="plasma_r")
            axes[8 * j + 1].imshow(gt_depth, cmap="jet_r", vmin=0, vmax=1)
            axes[8 * j + 1].axis('off')

for j in range(len(imgs)):
    idx = np.argmin(rmse[j])
    for i in range(len(model_list)):
        if i == idx:
            axes[8 * j + 2 + i].set_title("{:.3f}".format(rmse[j, i]), y=-0.16, size=36, fontweight='bold')
        else:
            axes[8 * j + 2 + i].set_title("{:.3f}".format(rmse[j, i]), y=-0.16, size=36)

plt.tight_layout()
plt.show()


# --- Code cell 4 ---
def compute_errors(gt, pred):
    thresh = np.maximum((gt / pred), (pred / gt))
    a1 = (thresh < 1.25).mean()
    a2 = (thresh < 1.25 ** 2).mean()
    a3 = (thresh < 1.25 ** 3).mean()

    rmse = (gt - pred) ** 2
    rmse = np.sqrt(rmse.mean())

    rmse_log = (np.log(gt) - np.log(pred)) ** 2
    rmse_log = np.sqrt(rmse_log.mean())

    abs_rel = np.mean(np.abs(gt - pred) / gt)

    sq_rel = np.mean(((gt - pred) ** 2) / gt)

    return [abs_rel, sq_rel, rmse, rmse_log, a1, a2, a3]


for i, model_name in enumerate(model_list):
    print(model_name)
    print("\n  " + ("{:>8} | " * 7).format("abs_rel", "sq_rel", "rmse", "rmse_log", "a1", "a2", "a3"))
    for j, img in enumerate(imgs):
        pred_depth = model_pred_depths[i][j]
        fig, axes = plt.subplots(1, 1)
        fig.set_size_inches(10, 10)
        # axes.imshow(1-pred_depth, vmin=0, vmax=1)
        axes.imshow(pred_depth, cmap="jet_r", vmin=0, vmax=1)
        axes.axis('off')
        fname_colormap = "_".join(model_name.split("/")) + "_".join(img.split("/")[-2:] + ["colormap.png"])
        plt.savefig(os.path.join("pred_color_map", fname_colormap), bbox_inches='tight', pad_inches=0)

        gt_depth = cv2.imread(img.replace("color.png", "depth.tiff"), -1) / (2 ** 16 - 1)
        fig, axes = plt.subplots(1, 1)
        fig.set_size_inches(10, 10)
        # axes.imshow(1-pred_depth, vmin=0, vmax=1)
        axes.imshow(pred_depth - gt_depth, cmap="seismic_r", vmin=-1, vmax=1)
        axes.axis('off')
        fname_divergingmap = "_".join(model_name.split("/")) + "_".join(img.split("/")[-2:] + ["divergingmap.png"])
        plt.savefig(os.path.join("pred_diverging_map", fname_divergingmap), bbox_inches='tight', pad_inches=0)

        mean_errors = compute_errors(gt_depth, pred_depth)
        print(("&{: 8.3}  " * 7).format(*mean_errors))

# --- Code cell 5 ---

fig, axes = plt.subplots(1, 1)
fig.set_size_inches(10, 6)
# axes.imshow(1-pred_depth, vmin=0, vmax=1)
im = axes.imshow(pred_depth - gt_depth, cmap="seismic_r", vmin=-1, vmax=1)
plt.colorbar(im, ax=axes, aspect=12, drawedges=False, ticks=[-1, 0, 1])
